model:
  spatial_dims: 3
  features:  [64, 64, 128, 128, 256, 256] # [16,32,64,128,256,256]
  upsample_features: 64
  strides: [2, 2, 2, 2, 2, 2]
  dropout: 0.3
  activation: "ReLU"
  dropout: 0.3
  bias: True
  norm: "Instance"