context_csv_path: "data/test.csv"
input_size: [64,64,64]
output_size: [128,128,128]
use_accelerator: True
augmentation: True
base_path: "./"
augmentation_params:
  rotation_range: [90,90,90]
  p_rotation: 0.5
  min_zoom: 0.9
  max_zoom: 1.3
  p_zoom: 0.5
  p_flip: 0.5
  noise_std: 0.1
  p_noise: 0.1
  smooth_sigma: [0.25, 0.1]
  p_smooth: 0.1
  p_intensity_scale: 0.3
  intensity_scale_factors: 0.2
  p_intensity_shift: 0.3
  intensity_shift_offsets: 0.1
  p_contrast: 0.3
  contrast_gamma: 4
model:
  name: "BasicUNet"
  spatial_dims: 3
  features: [32, 32, 64, 128, 256, 32]
  activation: "LeakyReLU"
  dropout: 0.3
  bias: True
  normalization: "instance"




