context_csv_path: "data/train.csv"
input_size: [64,64,64]
use_accelerator: True
augmentation: True
base_path: "./"
seed: 2001
augmentation_params:
  rotation_range: [45,45,45]
  p_rotation: 0.8
  min_zoom: 0.9
  max_zoom: 1.1
  p_zoom: 0.5
  p_flip: 0.5
  noise_std: 0.1
  p_noise: 0.5
  smooth_sigma: [0.25, 0.1]
  p_smooth: 0.5
  p_intensity_scale: 0.5
  intensity_scale_factors: 0.2
  p_intensity_shift: 0.5
  intensity_shift_offsets: 0.1
  p_contrast: 0.3
  contrast_gamma: 4
model:
  spatial_dims: 3
  features: [64,64,128,128,256,256]
  strides: [2, 2, 2, 2, 2, 2]
  dropout: 0.3
  activation: "ReLU"
  dropout: 0.3
  bias: True
  norm: "Instance"
trainer:
  device: "cuda"
  batch_size: 32
  num_workers: 8
  epochs: 10
  shuffle: True
  name: "BasicUNet_No_padding_L1_loss"
  test_metrics: ["L1", "MSE"]
  epochs_between_safe: 1
  batches_between_safe: 200
  split_random: False
  tensorboard_path: "tensorboard"




